cloud:
  aws:
    credentials:
      access-key: your Key
      secret-key: your Key
    region:
      static: Your cloud region
    stack:
      auto: false

application:
  bucket:
    name: your bucket name

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
